server:
  port: 9092

spring:
  application:
    name: consumer-service

eureka:
  client:
    service-url:
      defaultZone: HTTP://127.0.0.1:10086/eureka

#ribbon:
#  ConnectTimeout: 1000 # 连接超时时长
#  ReadTimeout: 5000 # 数据通信超时时长
#  MaxAutoRetries: 0 # 当前服务器的重试次数
#  MaxAutoRetriesNextServer: 0 # 重试多少次服务
#  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试